version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notsphere
    ports:
      - '5432:5432'
  minio:
    image: minio/minio:RELEASE.2023-08-29T23-07-35Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '8025:8025'
volumes:
  minio-data:
