version: '3.9'
services:
  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    env_file:
      - ../apps/api/.env
    depends_on:
      - postgres
      - minio
  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    environment:
      - VITE_API_URL=/api
    depends_on:
      - api
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notsphere
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2023-08-29T23-07-35Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
  nginx:
    image: nginx:1.25
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - api
      - web
volumes:
  postgres-data:
  minio-data:
